# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  (1..2).each do |i|
   config.vm.define "web-#{i}" do |web|
     web.vm.box = "hashicorp/bionic64"
     web.vm.hostname = "web-#{i}"
     web.vm.network "private_network", ip: "192.168.33.#{i}"
     web.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1", "--name", "web-#{i}"]
     end
     web.vm.provision "shell", inline: "echo Let's do this"
   end
  end

  config.vm.define "db" do |db|
   db.vm.box = "hashicorp/bionic64"
   db.vm.hostname = "db"
   db.vm.network "private_network", ip: "192.168.33.100"
   db.vm.provision "shell", inline: "echo Hallo, Ima DB server"
  end
end

