- hosts: webservers
  become: true
  tasks: 
            -name: "Install epel repository"
            yum: 
                name: epel-release
            -name: "Install nginx"
              yum:
                  name: nginx
                  state: installed
            -name: "Start nginx"
              service:
                  name: nginx
                  state: started
                  enabled: yes
            -name: "Configure nginx"
              template:
                  src: templates/index.j2
                  dest: {{ path_page }}/index.html
                  owner: root
                  group: wheel
                  mode: "0644"
            - name: "Task Hostname"
              shell: "echo $HOSTNAME"
              register: print_hostname
            - name: "Task Free RAM"
              shell: "free -m | awk '{print $4}' | sed -n 2p"
              register: free_ram
            - name: "Task Date"
              shell: "date"
              register: print_date