variable1: "deploit load balancer"
variable2: "deploit two web servers"
variable3: "deploit one db ... because yes ..."
variable4: "use Vim for all"
variable5: "add fancy RAM memory status bar in this page"
