---
- hosts: master
  become: true
  tasks:
    - name: Start the service
      systemd:
        name: glusterd
        state: started
        
    - name: Add node1 
      shell: sudo gluster peer probe node1

    - name: Add node2 
      shell: sudo gluster peer probe node2

    - name: Create the volume 
      shell: sudo gluster volume create gv0 replica 3 master:/data node1:/data node2:/data force

    - name: Start it
      shell: sudo gluster volume start gv0

